- name: configuring the rabbitmq
  hosts: rabbitmq
  become: yes
  tasks: 
  - name : copying the rabbitmq repo
    ansible.builtin.copy:
    src: rabbitmq.service
    dest: vim /etc/yum.repos.d/rabbitmq.repo
  
  - name: installing the rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: present
  
  - name:  start and enable the rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started 
      enabled: yes
      
  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop 
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present