- name : roboshop
  hosts: all
  connection: local
  vars:
    sg_id: sg-0d9028f369846db6c
    ami_id: ami-0220d79f3f480ecf5
    env: dev 
    instances:
      - mangodb
      - catalogue
  tasks:
  - name: create an aws ec2 instance
    amazon.aws.ec2_instance:
      name: "{{item}}-{{env}}"
      instance_type: "t3.micro"
      security_group: sg_id
      image_id: ami_id
      tags:
        Project: roboshop
        Component: "{{ item }}"
        env: "{{ env }}"
        Name: "{{ item }}-{{ env }}"
    
    loop: "{{instances}}"
    register: ec2_output 

  - name : print the  output 
    ansible.builtin.debug:
      msg: " {{ ec2_output }}"
