- name : user configuring 
  hosts: user
  become : yes 

  tasks:
  - name : enableing  nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs:20
    ansible.builtin.dnf:
      name: nodejs
      state: present  

  - name: 
    ansible.builtin.user:
      name: roboshop
      system: true
      shell: /sbin/nologin
      home : /app
      comment: roboshop system user

  - name: Delete app directory
    ansible.builtin.file:
      path: /app
      state: absent
      
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: deleteing zip file 
    ansible.builtin.file:
      path: /tmp/user.zip
      state:  absent
       

  - name: download user
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
      dest: /tmp/user.zip

  - name: unarchieve user
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  # - name : downloading application code
  #   ansible.builtin.get_url:
  #     url:  https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
  #     dest: /tmp/user.zip

  # - name : unzip the code
  #   ansible.builtin.unarchive:
  #     src : /tmp/user.zip
  #     dest: /app 


  - name: installing dependecies
    community.general.npm:
      path: /app
  - name: copying user service
    ansible.builtin.template:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name : damon reload after changes
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start user
    ansible.builtin.service:
      name: user
      state: restarted # restarted is a safe option 
      enabled: yes